#!/usr/bin/env bash
#  transfer a file to server
len_ofargs () {
    num=0
    for i in "$@"; do
        ((num++))
    done
    return $num
}
len_ofargs "$@"

num=$?
if (num < 3)
then
    echo -e "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -o StrictHostKeyChecking=0 -i $4 $1 $3@$2:~/
fi
