#!/usr/bin/env bash
#   transfer file to a server:
args() {
    ((l = 0))
    for item in $@; do
        ((l++))
    done
    return $num
}
args $@
((num = $?))
if ((num < 3)); then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
fi
