#!/usr/bin/env bash
# Transfer a file to server

len_ofargs() {
    num=0
    for _ in "$@"; do
        ((num++))
    done
    echo "$num"
}

num_args=$(len_ofargs "$@")
if ((num_args < 4)); then
    echo -e "\e[31;45;7;3mUsage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY\e[0m"
    exit 1
else
    scp -o StrictHostKeyChecking=0 -i "$4" "$1" "$3"@"$2":~/
fi

