#!/usr/bin/env bash
#   Install nginx
#   khalidovitch
sudo apt upgrade -y
sudo apt install nginx -y
sudo chown -R ubuntu /var/www/
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
