#!/usr/bin/env bash
# install nginx


sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo touch /var/www/html/index.html
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx restart
