#!/usr/bin/env bash
# redirection

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo chown -R ubuntu /var/www/
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

sudo sed -i '78i\
\tlocation /redirect_me {\
\t\treturn 301 https://translate.google.co.ma/?hl=fr\&sl=auto\&tl=ar\&op=translate;\
\t\t# this is a redirection of the traduction web site\
\t\t# i khalid and iam do that in server config\
\t}' /etc/nginx/sites-available/default

sudo service nginx start

