#!/usr/bin/env bash
# Update package lists and upgrade existing packages
sudo apt -y update
sudo apt -y upgrade

# Install Nginx web server
sudo apt -y install nginx

# Start Nginx service
sudo service nginx start

# Allow HTTP traffic through UFW firewall for Nginx
sudo ufw allow 'Nginx HTTP'

# Set appropriate ownership and permissions for Nginx web directory
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Create a backup of the default Nginx index page
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Write "Hello World!" to the default Nginx index page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Add a custom 404 error page to the Nginx server
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo sed -i '52i\       error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes in the configuration
sudo service nginx restart
