#!/usr/bin/env bash
# Use the bash shell to execute this script

# Create a custom 404 error page with the text "Ceci n'est pas une page" and save it to /var/www/html/custom_404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Insert a line at line 46 in the Nginx configuration file to define the custom 404 error page
sed -i '52i\    # Placeholder for custom error page' /etc/nginx/sites-available/default
sed -i '53i\    error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
# Restart the Nginx service to apply the changes
service nginx restart
