#!/usr/bin/env bash
# set up web_02 to be identical as web_01

# Update and install Nginx
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx

# Create index.html with "Hello World!"
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Backup the default Nginx config file
sudo cp /etc/nginx/sites-available/default ~/backups/available_default

# Insert redirect configuration for task 3
sudo sed -i '14i\# this is for task 3 in 0x0C-web_server\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default

# Create custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html

# Add custom error page handling to Nginx config
sudo sed -i '19i\error_page 404 /error_404.html;\n' /etc/nginx/sites-available/default

# Add custom header for load balancer task
sudo sed -i '21i\add_header X-Served-By $hostname; # Add custom header 0x0F-load_balancer TASK 0\n' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

