#!/usr/bin/env bash
# set up web_02 to be identical as web_01

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo touch /var/www/html/index.html
echo 'Hello World!' | sudo tee /var/www/html/index.html
# backup the file if an error occurs
cp /etc/nginx/sites-available/default ~/backups/available_default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html

printf %s "server {
    listen 80;
    listen [::]:80;
    add_header X-Served-By $HOSTNAME;
    root /var/www/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
