#!/usr/bin/env bash

# install HAproxy in my lb-01 server.
sudo apt -y update
sudo apt -y install haproxy
sudo systemctl start haproxy


# config file for HAProxy
path="/etc/haproxy/haproxy.cfg"

sudo bash -c "cat <<EOF >> /etc/haproxy/haproxy.cfg

frontend khalid77.tech # for example
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 510461-web-01 100.27.0.26:80 check
    server 510461-web-02 54.90.56.60:80 check
EOF"

sudo sed -i "9i ENABLED=1" /etc/default/haproxy
sudo service haproxy restart
