#!/usr/bin/env bash
# install HAproxy in my lb-01 server.
sudo apt -y update
sudo apt -y install haproxy
sudo service haproxy start

# backup
cp /etc/haproxy/haproxy.cfg ~/backups/haproxy.cfg
cp /etc/default/haproxy ~/backups/haproxy

# config file for HAProxy
sudo echo -e 'frontend khalid_loug\n\tbind *:80\n\tdefault_backend web_servers\n\nbackend web_servers\n\tbalance roundrobin\n\tserver 510461-web-01 34.203.38.10:80 check\n\tserver 510461-web-02 54.175.223.87:80 check\n' | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo bash -c 'echo "ENABLED=1" >> /etc/default/haproxy'
sudo service haproxy restart
