#!/usr/bin/env bash
# Setup master and slave servers

# make sure to allow connections about two servers
sudo ufw allow 3306

# Define configuration data for master and slave servers
config_data_01="\
# a lot of comment removed here
[mysqld]
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
datadir         = /var/lib/mysql
log-error       = /var/log/mysql/error.log

# By default we only accept connections from localhost
# bind-address    = 127.0.0.1

# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links  = 0 # changed by khalid

# this is changed values for the project (0x14-mysql)
server-id       = 1 # changed by khalid
binlog_do_db    = tyrell_corp # changed by khalid
log_bin         = /var/log/mysql/mysql-bin.log\
"

config_data_02="\
# a lot of comment removed here
[mysqld]
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
datadir         = /var/lib/mysql
log-error       = /var/log/mysql/error.log

# By default we only accept connections from localhost
# bind-address   = 127.0.0.1 # chnaged

# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links  = 0

# this is changed values for the project (0x14-mysql)
server-id       = 2 # changed
log_bin         = /var/log/mysql/mysql-bin.log
binlog_do_db    = tyrell_corp # changed
relay-log       = /var/log/mysql/mysql-relay-bin.log\
"

# Get the server's hostname
server_name=$(hostname)

# Check the server name and apply the appropriate configuration
if [[ "$server_name" == "510461-web-01" ]]; then
    echo "$config_data_01" | sudo dd status=none of=/etc/mysql/mysql.conf.d/mysqld.cnf
    server_display_name="web_01"
elif [[ "$server_name" == "510461-web-02" ]]; then
    echo "$config_data_02" | sudo dd status=none of=/etc/mysql/mysql.conf.d/mysqld.cnf
    server_display_name="web_02"
else
    echo "Not in appropriate server"
    exit 1
fi

# Restart MySQL service
sudo service mysql restart

# Print success message with the name of the server
echo "Done with $server_display_name"
