#!/usr/bin/env bash
# print "Best School" 10 time using while
# and print hi between iter 9 & iter 10

i=0

while (( i < 10 ))
do
        echo "Best School"
        ((i++))
        if (( i == 9));
        then
                echo "hi"
        fi
done
