#!/usr/bin/env bash
#print "Best School" 20 time using while
#and print some 'words' in special 'iter' using case
i=0
while (( i < 20 ))
do
        ((i++))
        case $i in
                5)
                        echo "bad luck from China"
                        ;;
                10)
                        echo "bad luck from Japan"
                        ;;
                18)
                        echo "bad luck from Italy"
                        ;;
        esac
        echo "$i"
done
