#!/usr/bin/env bash
# allow only some incoming traffic

sudo apt update -y && sudo apt upgrade -y
sudo apt install ufw
ufw enable
ufw allow 22
ufw allow 443
ufw allow 80
sudo ufw default deny incoming
sudo ufw default allow outgoing
