#!/usr/bin/env bash
# 


# Backup the original file
sudo cp /etc/ufw/before.rules /etc/ufw/before.rules.backup

# Insert the new rules at line 11
sudo sed -i '11i \
*nat\n\
:PREROUTING ACCEPT [0:0]\n\
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\n\
COMMIT' /etc/ufw/before.rules

sudo vi /etc/ufw/before.rules # to check
sudo ufw allow 8080

# Reload UFW to apply the changes
sudo ufw reload
