#!/usr/bin/env bash
# forward a port to another port

sed -i '10 s/^#//' /etc/ufw/sysctl.conf
sudo sysctl -p

sudo iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 8080 -j REDIRECT --to-port 80
sudo ufw enable
