#!/bin/bash

# Gracefully reload Gunicorn by sending the HUP signal to the master process
# The HUP signal tells Gunicorn to reload the configuration and restart workers

# Find the Gunicorn master process ID
MASTER_PID=$(ps aux | grep 'gunicorn' | grep 'master' | awk '{print $2}')

# Send the HUP signal to the master process to reload Gunicorn gracefully
if [ -n "$MASTER_PID" ]; then
    kill -HUP "$MASTER_PID"
    echo "Gunicorn master process (PID: $MASTER_PID) has been reloaded."
else
    echo "Gunicorn master process not found."
fi
