#!/usr/bin/env bash
# connect to the server using private_key instead of password


# user="ubuntu"
# private_key_path="~/.ssh/school"
# server="54.237.3.226"

ssh -i ~/.ssh/school ubuntu@34.203.38.10
