#!/usr/bin/env bash
# define variables
user="ubunt"
private_key="~/.ssh/school"
server="18.209.224.148"
# SSH connection using single-character flags
ssh -i "$private_key" $user@$server
# ssh -i ~/.ssh/school ubuntu@192.168.1.100 
