#!/usr/bin/env bash
# script that creates an RSA key pair.
name="school"
passphrase="betty"
bits="4096"

ssh-keygen -b "$bits" -t rsa -f "$name" -N "$passphrase"

# ssh-keygen -b 4096 -t rsa -f "school" -N "betty"
